### ISSUE TITLE
What technologies will we develop on the front?

### ISSUE THREAD

**Issue by guilhermedinardi** [PhelipeLB/Cosvesi-project#36]
- [ ] React
- [ ] Relay
- [ ] Next
- [ ] Vue

**Comment by daniloab** [comment]
I would advice to use nextjs. Simpler and easier. Follow this https://github.com/daniloab/service-guru

**Comment by guilhermedinardi** [comment]
I see in the project that we have a next installed, should we follow this one or create a new?

**Comment by daniloab** [comment]
> I see in the project that we have a next installed, should we follow this one or create a new?

this one, my link it was just an example

**Comment by guilhermedinardi** [comment]
yes, but in this repo already exists next

**Comment by daniloab** [comment]
> yes, but in this repo already exists next

so, do we need this issue?

**Comment by guilhermedinardi** [comment]
I saw the stack after creating the issue

**Comment by daniloab** [comment]
> I saw the stack after creating the issue

lets go
